# Generated by Django 4.2.6 on 2025-01-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
