# Generated by Django 5.1.4 on 2025-01-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundindex',
            name='initial_nav',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='fundindex',
            name='total_units',
            field=models.FloatField(default=50000),
        ),
    ]
