# Generated by Django 5.1.4 on 2025-01-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_fundindex_initial_nav_fundindex_total_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
    ]
