# Generated by Django 5.1.4 on 2025-01-10 08:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_stock_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='NAVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('value', models.FloatField()),
                ('fund_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_data', to='admin_panel.fundindex')),
            ],
            options={
                'unique_together': {('fund_index', 'date')},
            },
        ),
    ]
